# The name of this application, which must be unique within a project.
name: 'frontend'

# The type key specifies the language and version for your application.
type: 'nodejs:14'

dependencies:
  nodejs:
    yarn: "^1.22.0"

relationships:
  backend: 'backend:http'

mounts:
  '/.cache':
    source: local
    source_path: 'cache'
  '/.config':
    source: local
    source_path: 'config'
  '/.next':
    source: local
    source_path: 'next'
  '/__generated__':
    source: local
    source_path: '__generated__'

# The hooks that will be triggered when the package is deployed.
hooks:
  build: |
    set -e
    yarn
    yarn global add apollo --prefix /usr/local

  post_deploy: |
    set -e
    yarn codegen

# The size of the persistent disk of the application (in MB).
disk: 1024

# The configuration of the application when it is exposed to the web.
web:
  commands:
    start: npx next start -p $PORT