# The name of this application, which must be unique within a project.
name: 'frontend'

# The type key specifies the language and version for your application.
type: 'nodejs:14'

dependencies:
  nodejs:
    yarn: "^1.22.0"

relationships:
  backend: 'backend:http'

# The hooks that will be triggered when the package is deployed.
hooks:
  build: |
    yarn
    yarn build

# The size of the persistent disk of the application (in MB).
disk: 500

# The configuration of the application when it is exposed to the web.
web:
  commands:
    start: npx next dev -p $PORT

mounts:
  '/.config':
    source: local
    source_path: config
  '/.global':
    source: local
    source_path: global
  '/.next':
    source: local
    source_path: next