version: "3"

services:
  frontend:
    image: deeson/fe-node
    container_name: "northants_frontend"
    volumes:
      - ./:/app:delegated
    working_dir: /app
    environment:
      DOCKER_LOCAL: 1
    command: bash -c 'yarn && yarn dev'
    networks:
      - default
      - proxy
    labels:
      - 'traefik.docker.network=proxy'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:northants.localhost'
  codegen:
    image: deeson/fe-node
    container_name: "northants_codegen"
    volumes:
      - ./:/app:delegated
    working_dir: /app
    environment:
      DOCKER_LOCAL: 1
    command: bash -c 'yarn codegen'
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
