version: "3"

services:
  mariadb:
    image: wodby/mariadb:10.3-3.12.4
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    ports:
#      - "3307:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - default

  solr:
    image: $SOLR_TAG
    container_name: "${PROJECT_NAME}_solr"
    environment:
      SOLR_HEAP: 1024m
    volumes:
      - solr:/opt/solr/server/solr/main
    networks:
      - default
    labels:
      - 'traefik.docker.network=proxy'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.${PROJECT_BASE_URL}'

  php:
    image: wodby/drupal-php:7.4-4.24.4
    container_name: "${PROJECT_NAME}_php"
    environment:
      DOCKER_LOCAL: 1
      D4D_HOSTNAME: ${PROJECT_BASE_URL}
      DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT}
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      NEXT_PUBLIC_THEME: west
      CLOUDFLARE_EMAIL: test@test.com
      CLOUDFLARE_API_KEY: test
      CLOUDFLARE_ZONE_ID: test
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_FPM_CLEAR_ENV: "no"
      COLUMNS: 80
      PHP_IDE_CONFIG: "serverName=drupal"       # Needed for xdebug for drush commands.
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
      #PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
      #PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03, You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
      #PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
      #PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
    volumes:
      - ./:/var/www/html:delegated
      - files:/mnt/files
    tmpfs: /tmp
    networks:
      - default

  nginx:
    image: wodby/nginx:1.19-5.13.7
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_STATIC_404_TRY_INDEX: 1 # Needed for Stage file proxy to work
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
      NGINX_VHOST_PRESET: drupal9
    volumes:
      - ./:/var/www/html:delegated
      - files:/mnt/files
    tmpfs: /tmp
    networks:
      - default
      - proxy
    labels:
      - 'traefik.docker.network=proxy'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    networks:
      - default
      - proxy
    labels:
      - 'traefik.docker.network=proxy'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

  redis:
    image: wodby/redis:5-3.7.4
    container_name: "${PROJECT_NAME}_redis"
    networks:
      - default

networks:
  proxy:
    external: true

volumes:
  mariadb:
  solr:
  files:
