<?php

/**
 * @file
 *
 * Hook implementations for the nc_nodes module.
 */

use Drupal\Core\Site\Settings;
use Drupal\Core\Url;
use GuzzleHttp\Exception\RequestException;
use Ramsey\Uuid\Uuid as UuidLib;
use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function nc_nodes_form_node_form_alter(&$form, &$form_state, $form_id) {
  // Change submit button text on the node edit form.
  $router_item = \Drupal::routeMatch()->getRouteName();

  if ($router_item === 'entity.node.edit_form' || $router_item === 'node.add') {
    $form['actions']['submit']['#value'] = t('Save and close');

    // Set the default moderation state to draft
    $form['moderation_state']['widget'][0]['state']['#default_value'] = 'draft';

    if (!empty($form['publish_state']['widget'][0]['#options']['published'])) {
      $form['publish_state']['widget'][0]['#default_value'] = 'published';
    }

    if (!empty($form['unpublish_state']['widget'][0]['#options']['archived'])) {
      $form['unpublish_state']['widget'][0]['#default_value'] = 'archived';
    }
  }

  // Remove the body label.
  if (!empty($form['body'])) {
    $form['body']['widget'][0]['#title'] = '';
  }

  // Set 'Unpublish on' date for news articles
  if ($form_id === 'node_news_article_form') {
    $currentTime = new DrupalDateTime('now');
    $unpublishDate = $currentTime->modify('+ 2 years');
    $form['unpublish_on']['widget'][0]['value']['#default_value'] = $unpublishDate;
  }

  // If 'Promoted to front page' option is selected, make featured image required.
  if ($form_id === 'node_news_article_form' || $form_id === 'node_news_article_edit_form') {
    $form['#validate'][] = 'nc_nodes_form_node_validate_promoted';
  }

  $forms_list = [
    'node_service_landing_page_form',
    'node_service_landing_page_edit_form',
    'node_service_page_form',
    'node_service_page_edit_form'
  ];

  if (in_array($form_id, $forms_list) ) {
    $form['#validate'][] = 'nc_nodes_form_node_validate_date_time';
  }

}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function nc_nodes_node_presave(Drupal\node\Entity\Node $node) {
  if (!$node->hasField('body') || !$node->hasField('field_page_slices')) {
    return;
  }

  $embedded_paragraphs = [];

  /** @var \Drupal\nc_nodes\EmbeddedParagraphsService $paragraphs_service */
  $paragraphs_service = \Drupal::service('nc_nodes.embedded_paragraphs');

  /** @var \Drupal\text\Plugin\Field\FieldType\TextLongItem $body */
  $body = $node->get('body')[0];

  if (empty($body)) {
    // Can be null if they've not put anything in the field.
    return;
  }

  $html = $body->getValue();

  foreach ($paragraphs_service->getParagraphsFromHTML($html['value']) as $embedded_paragraph) {
    if (!in_array($embedded_paragraph, $embedded_paragraphs)) {
      $embedded_paragraphs[] = $embedded_paragraph;
    }
  }

  $node->field_page_slices = $embedded_paragraphs;
}

/**
 * Implements hook_ENTITY_TYPE_validate().
 * This function validates field_revision_date and returns an error if the date is greater than two years from today's date
 */
function nc_nodes_form_node_validate_date_time($form, &$form_state) {
  $now = new DrupalDateTime('now');
  $max_date =  $now->modify('+2 year');
  $max_date = $max_date->format('Y-m-d');

  if ($form_state->getValue('field_revision_date')[0]['value']) {
    $date = $form_state->getValue('field_revision_date')[0]['value']->format('Y-m-d');
    if ($date > $max_date) {
      $form_state->setErrorByName('field_revision_date', 'The review date cannot be greater than 2 years from now.');
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_validate().
 * This function validates field_featured_image and returns an error if the
 * field is unset and the promoted to frontpage option has been checked.
 */
function nc_nodes_form_node_validate_promoted($form, &$form_state) {
  $promoted = $form_state->getValue('promote')['value'];
  if ($promoted) {
    $featured_image = array_key_exists('selection', $form_state->getValue('field_featured_image'));
    if (($featured_image === FALSE)) {
      $form_state->setErrorByName('field_featured_image', 'A featured image must be selected if "Promoted to front page" is checked.');
    }
  }
}
