<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\node\Entity\Node;

/**
 * Implements hook_cron().
 *
 */
function nc_workflow_cron() {
  $user_tz = date_default_timezone_get();
  $now = new DrupalDateTime('now', $user_tz);
  $now = $now->format('Y-m-d');

  if( date('G') == 04){
    \Drupal::logger('nc_workflow_cron')->notice('nc_workflow cron ran');

    $query = \Drupal::entityQuery('node')
      ->condition('type', ['service_landing_page', 'service_page'], 'in')
      ->condition('field_revision_date', $now, '<')
      ->condition('status', 1);
    $results = $query->execute();

    if (!empty($results)) {
      foreach ($results as $node_id) {
        $node = Node::load($node_id);
        $node->status = 0;
        $node->setPublished(FALSE);
        $node->set('moderation_state', "archived");
        $node->save();
      }
    }
  }
}
