# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "frontend:http"
#  cache:
#    enabled: true
#    default_ttl: 3600
#    cookies: [ '*' ]
#    headers: [ 'Accept', 'Accept-Language' ]

# "https://www.{default}/":
#   type: redirect
#   to: "https://{default}/"
