# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://beta.{default}/":
  type: upstream
  upstream: "frontend:http"
#  cache:
#    enabled: true
#    default_ttl: 3600
#    cookies: [ '*' ]
#    headers: [ 'Accept', 'Accept-Language' ]

# "https://www.{default}/":
#   type: redirect
#   to: "https://{default}/"

"https://cms.{default}/":
  type: upstream
  upstream: "backend:http"
  cache:
    enabled: true
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
