<?php

use Drupal\config_pages\Entity\ConfigPages;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\nc_system\Entity\Paragraph\BlockQuote;
use Drupal\nc_system\Entity\Paragraph\CallToAction;
use Drupal\nc_system\Entity\Node\Homepage;
use Drupal\nc_system\Entity\Node\Article;
use Drupal\nc_system\Entity\Node\ServicePage;
use Drupal\nc_system\Entity\Node\ServiceLandingPage;
use Drupal\nc_system\Entity\Paragraph\CouncilSignpost;
use Drupal\nc_system\Entity\Paragraph\CouncilSignposting;
use Drupal\nc_system\Entity\Paragraph\Section;
use Drupal\nc_system\Entity\Paragraph\ServiceLinks;
use Drupal\nc_system\Entity\Paragraph\Accordion;
use Drupal\nc_system\Entity\Paragraph\AccordionItem;
use Drupal\nc_system\Entity\Paragraph\FileDownload;
use Drupal\nc_system\Entity\Paragraph\PromoBanner;
use Drupal\nc_system\Entity\TaxonomyTerm\SovereignCouncil;
use Drupal\node\Entity\Node;
use Drupal\system\Entity\Menu;

/**
 * Implements hook_entity_bundle_info_alter().
 *
 * Changes the bundle classes used by drupal, so when when an entity of
 * a specific bundle is loaded, one of the below classes is used.
 * @param array $bundles
 */
function nc_system_entity_bundle_info_alter(array &$bundles) {
  // Node bundles
  $bundles['node']['homepage']['class'] = Homepage::class;
  $bundles['node']['news_article']['class'] = Article::class;
  $bundles['node']['service_page']['class'] = ServicePage::class;
  $bundles['node']['service_landing_page']['class'] = ServiceLandingPage::class;

  // Paragraph bundles
  $bundles['paragraph']['call_to_action']['class'] = CallToAction::class;
  $bundles['paragraph']['council_signpost']['class'] = CouncilSignpost::class;
  $bundles['paragraph']['council_signposting']['class'] = CouncilSignposting::class;
  $bundles['paragraph']['pull_quote']['class'] = BlockQuote::class;
  $bundles['paragraph']['section']['class'] = Section::class;
  $bundles['paragraph']['service_links']['class'] = ServiceLinks::class;
  $bundles['paragraph']['accordion']['class'] = Accordion::class;
  $bundles['paragraph']['accordion_item']['class'] = AccordionItem::class;
  $bundles['paragraph']['file_download']['class'] = FileDownload::class;
  $bundles['paragraph']['promotional_banner']['class'] = PromoBanner::class;

  // Taxonomy terms
  $bundles['taxonomy_term']['sovereign_councils']['class'] = SovereignCouncil::class;

}

/**
 * @param EntityTypeInterface[] $entity_types
 */
function nc_system_entity_type_alter(&$entity_types) {
  if (isset($entity_types['embedded_paragraphs'])) {
    // Use our own EmbeddedParagraphs class which supports GraphQL entity field resolution.
    $entity_types['embedded_paragraphs']->setClass('Drupal\nc_system\Entity\EmbeddedParagraphs');
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * Changes the admin toolbar colour
 * @param array $variables
 */
function nc_system_page_attachments_alter(array &$page) {
  $admin_theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();

  if ($admin_theme === 'nc_seven') {
    $background_color = \Drupal::service('nc_system.website_manager')->getBackgroundColor();

    if (!empty($background_color)) {
      $css = "#toolbar-administration .toolbar-bar { background-color: $background_color; }";
      $page['#attached']['html_head'][] = [
        [
          '#tag' => 'style',
          '#value' => $css,
        ],
        'admin-toolbar-custom-css'
      ];
    }
  }
}

/**
 * This function purges the Cloudflare cache on menu updates.
 * @param Menu $menu
 */
function nc_system_menu_update(Menu $menu) {
  if ($menu->id() === 'footer') {
    $purge_service = \Drupal::service('nc_cloudflare_purge.service');
    $purge_service->purgeAll();
  }
}

/**
 * This function purges the Cloudflare cache on creating new menu links.
 * @param MenuLinkContent $entity
 */
function nc_system_menu_link_content_insert(MenuLinkContent $entity) {
  _purge_menu($entity);
}

/**
 * This function purges the Cloudflare cache on updating menu links.
 * @param MenuLinkContent $entity
 */
function nc_system_menu_link_content_update(MenuLinkContent $entity) {
  _purge_menu($entity);
}

/**
 * This function purges the Cloudflare cache on deleting menu links.
 * @param MenuLinkContent $entity
 */
function nc_system_menu_link_content_delete(MenuLinkContent $entity) {
  _purge_menu($entity);
}

/**
 * This function purges the Cloudflare cache on menu links.
 * @param MenuLinkContent $entity
 */
function _purge_menu(MenuLinkContent $entity) {
  if ($entity->getMenuName() === 'footer') {
    $purge_service = \Drupal::service('nc_cloudflare_purge.service');
    $purge_service->purgeAll();
  }
}

/**
 * This function purges the Cloudflare cache when updating the sitewide alerts.
 * @param ConfigPages $entity
 */
function nc_system_config_pages_update(ConfigPages $entity) {
  $type = $entity->get('type')->target_id;

  if ($type === 'sitewide_alerts') {
    $purge_service = \Drupal::service('nc_cloudflare_purge.service');
    $purge_service->purgeAll();
  }
}

/**
 * This function purges the Cloudflare cache when updating the nodes.
 * @param Node $node
 */
function nc_system_node_update(Node $node) {
  $urls = [];
  $host = \Drupal::service('nc_system.website_manager')->getHost();
  $page_url = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $node->id());

  switch ($node->getType()) {
    case 'homepage':
      $urls[] = $host;
      break;

    case 'service_landing_page':
    case 'service_page':
      $urls[] = $host . $page_url;
      break;

    case 'news_article':
      $urls[] = $host . '/news';
      $urls[] = $host . $page_url;

      // if the news article is promoted we clear the homepage as well
      if ($node->isPromoted()) {
        $urls[] = $host;
      }

      break;
  }

  if (!empty($urls)) {
    $purge_service = \Drupal::service('nc_cloudflare_purge.service');
    $purge_service->purgeByUrl($urls);
  }
}

/**
 * Implements hook_xmlsitemap_element_alter().
 */
function nc_system_xmlsitemap_element_alter(&$element, array $link, $sitemap) {
  $replacement_url = parse_url(\Drupal::service('nc_system.website_manager')->getHost())['host'];
  $base_url = \Drupal::request()->getHost();
  $element['loc'] = str_replace($base_url, $replacement_url, $element['loc']);
}
