<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\nc_system\Entity\Paragraph\CallToAction;
use Drupal\nc_system\Entity\Node\ServicePage;
use Drupal\nc_system\Entity\Node\ServiceLandingPage;
use Drupal\nc_system\Entity\Paragraph\CouncilSignpost;
use Drupal\nc_system\Entity\Paragraph\CouncilSignposting;
use Drupal\nc_system\Entity\TaxonomyTerm\SovereignCouncil;

/**
 * Implements hook_entity_bundle_info_alter().
 *
 * Changes the bundle classes used by drupal, so when when an entity of
 * a specific bundle is loaded, one of the below classes is used.
 * @param array $bundles
 */
function nc_system_entity_bundle_info_alter(array &$bundles) {
  // Node bundles
  $bundles['node']['service_page']['class'] = ServicePage::class;
  $bundles['node']['service_landing_page']['class'] = ServiceLandingPage::class;

  // Paragraph bundles
  $bundles['paragraph']['call_to_action']['class'] = CallToAction::class;
  $bundles['paragraph']['council_signpost']['class'] = CouncilSignpost::class;
  $bundles['paragraph']['council_signposting']['class'] = CouncilSignposting::class;

  // Taxonomy terms
  $bundles['taxonomy_term']['sovereign_councils']['class'] = SovereignCouncil::class;

}

/**
 * @param EntityTypeInterface[] $entity_types
 */
function nc_system_entity_type_alter(&$entity_types) {
  if (isset($entity_types['embedded_paragraphs'])) {
    // Use our own EmbeddedParagraphs class which supports GraphQL entity field resolution.
    $entity_types['embedded_paragraphs']->setClass('Drupal\nc_system\Entity\EmbeddedParagraphs');
  }
}
